### ISSUE TITLE
Null byte error when reading parameters

### ISSUE THREAD

**Issue by CyrilWaechter** [pyrevitlabs/rsparam#1]
rsparam version : 0.1.12
Python version : 3.7.3
Install method : pip

It looks like it is still the same annoying NULL byte error in csv parser.
(Note : the shared parameter file has been created with Revit and is valid in Revit)
```python
>>> rsparam list -p shared_parameters.txt
source file: shared_parameters.txt
Traceback (most recent call last):
  File "c:\program files\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\program files\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Program Files\Python37\Scripts\rsparam.exe\__main__.py", line 9, in <module>
  File "c:\program files\python37\lib\site-packages\rsparam\cli.py", line 302, in main
    list_params(src_file)
  File "c:\program files\python37\lib\site-packages\rsparam\cli.py", line 79, in list_params
    sparams = rsparam.get_params(src_file, groupid=args['--filter'])
  File "c:\program files\python37\lib\site-packages\rsparam\__init__.py", line 147, in get_params
    spgroups, sparams = read_entries(src_file, encoding=encoding)
  File "c:\program files\python37\lib\site-packages\rsparam\__init__.py", line 92, in read_entries
    for line in csv.reader(spf, delimiter="\t"):
_csv.Error: line contains NULL byte
```

**Comment by eirannejad** [comment]
@CyrilWaechter Would you mind sharing the param file or explain how I can replicate this error? Does it happen on any txt file? Or the UTF-16 coming from Revit?

**Comment by CyrilWaechter** [comment]
It happens with any UTF-16 created with Revit. Here is a 1 parameter sample :
[TestFromRevit.txt](https://github.com/eirannejad/rsparam/files/3106273/TestFromRevit.txt)
I tried : 
`rsparam list -p TestFromRevit.txt` -> NULL byte error
`rsparam -e utf_16_le list -p TestFromRevit.txt` -> NULL byte error
I still get the same result.

But if I create a txt file like this encoded in utf-8 :
[TestManualUtf8.txt](https://github.com/eirannejad/rsparam/files/3106297/TestManualUtf8.txt)
`rsparam list -p "TestManualUtf8.txt"` -> Works
`rsparam -e utf-16-le list -p "TestManualUtf8.txt"` -> I don't understand why but it works

**Comment by eirannejad** [comment]
Okay let me take a look

**Comment by eirannejad** [comment]
Fixed. Wait a bit for pypi to index the new version and then `pip install -U rsparam`
